name: 'Fork Sync'
description: 'Keep your fork up to date'
author: 'TG908'
branding:
  icon: 'git-branch'
  color: 'black'
inputs:
  owner:
    description: 'Owner of the forked repository'
    required: false
  github_token:
    description: 'Token for the github API'
    required: true
  head:
    description: 'Branch to track'
    required: false
    default: 'master'
  base:
    description: 'Branch to keep updated'
    required: false
    default: 'master'
  merge_method:
    description: 'Merge method to use'
    required: false
    default: 'merge'
  pr_title:
    description: 'The title of the pull request'
    required: false
    default: 'Fork Sync'
  pr_message:
    description: 'The message in the pull request'
    required: false
  allbranches:
    description: 'Wheather sync all branches'
    required: false
    
runs:
  using: 'node12'
  main: 'lib/main.js'
